# -*- coding: utf-8 -*-
"""#1157.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EnDURLYLy6ferjrVQ_5cnAR71Q86Ujw7
"""

word = input().upper()
word_list = list(set(word))

list_ = []

for x in word_list :
    cnt = word.count(x)
    list_.append(cnt)
    
if list_.count(max(list_)) >= 2 :
    print("?")
    
else : 
    print(word_list[(list_.index(max(list_)))])